import {
  generateReverseShell,
  type ReverseShellConfig,
} from "@/lib/reverse-shells";

export interface BuiltinCollection {
  id: string;
  name: string;
  description: string;
  tags: string[];
  config: ReverseShellConfig;
  renderedCommand: string;
}

function preset(
  id: string,
  name: string,
  description: string,
  tags: string[],
  config: ReverseShellConfig,
): BuiltinCollection {
  return {
    id,
    name,
    description,
    tags,
    config,
    renderedCommand: generateReverseShell(config).command,
  };
}

export const builtinCollections: BuiltinCollection[] = [
  preset(
    "linux-bash-dev-tcp",
    "Linux Bash /dev/tcp",
    "Classic Bash reverse shell for Linux targets where Bash supports /dev/tcp.",
    ["linux", "bash", "classic"],
    {
      templateId: "bash-dev-tcp",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "/bin/bash",
      obfuscation: "none",
    },
  ),
  preset(
    "linux-nc-mkfifo",
    "Linux netcat mkfifo",
    "Portable netcat fallback for builds without the -e option.",
    ["linux", "nc", "fallback"],
    {
      templateId: "nc-mkfifo",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "/bin/sh",
      obfuscation: "none",
    },
  ),
  preset(
    "web-rce-python3",
    "Web RCE Python 3",
    "Python reverse shell suited for command injection and web RCE contexts.",
    ["multi", "python", "web-rce"],
    {
      templateId: "python3-socket",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "/bin/sh",
      obfuscation: "url",
    },
  ),
  preset(
    "web-rce-python",
    "Web RCE Python",
    "Unversioned Python reverse shell for targets where python is available.",
    ["multi", "python", "web-rce"],
    {
      templateId: "python-socket",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "/bin/sh",
      obfuscation: "url",
    },
  ),
  preset(
    "web-rce-python2",
    "Web RCE Python 2",
    "Python 2 reverse shell for legacy targets.",
    ["multi", "python", "web-rce"],
    {
      templateId: "python2-socket",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "/bin/sh",
      obfuscation: "url",
    },
  ),
  preset(
    "web-rce-php",
    "Web RCE PHP",
    "PHP proc_open payload for environments where PHP execution is available.",
    ["multi", "php", "web-rce"],
    {
      templateId: "php-proc-open",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "/bin/sh",
      obfuscation: "url",
    },
  ),
  preset(
    "linux-bash-obfuscated",
    "Obfuscated Bash base64",
    "Bash payload wrapped in base64 decode for filter-sensitive shells.",
    ["linux", "bash", "obfuscation"],
    {
      templateId: "bash-dev-tcp",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "/bin/bash",
      obfuscation: "bash-base64",
    },
  ),
  preset(
    "linux-bash-no-spaces",
    "Bash no-space ${IFS}",
    "Bash payload with spaces replaced by ${IFS} for simple space filters.",
    ["linux", "bash", "obfuscation"],
    {
      templateId: "bash-dev-tcp",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "/bin/bash",
      obfuscation: "bash-ifs",
    },
  ),
  preset(
    "windows-powershell-encoded",
    "Windows PowerShell encoded",
    "PowerShell TCPClient payload encoded as UTF-16LE base64 for -EncodedCommand.",
    ["windows", "powershell", "obfuscation"],
    {
      templateId: "powershell-tcp-client",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "powershell.exe",
      obfuscation: "powershell-encoded",
    },
  ),
  preset(
    "linux-socat-pty",
    "Linux socat PTY",
    "Socat payload that starts closer to an interactive TTY from the first callback.",
    ["linux", "socat", "tty"],
    {
      templateId: "socat-pty",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "/bin/bash",
      obfuscation: "none",
    },
  ),
  preset(
    "windows-hoaxshell-style",
    "Windows HoaxShell-style",
    "HTTP polling PowerShell callback for lab environments where raw TCP egress is blocked.",
    ["windows", "powershell", "http", "staged"],
    {
      templateId: "powershell-hoaxshell-style",
      lhost: "10.10.14.3",
      lport: 8080,
      shell: "powershell.exe",
      obfuscation: "none",
    },
  ),
  preset(
    "linux-curl-staged",
    "Linux curl staged",
    "Fetch a prepared rs.sh second-stage script from your HTTP server.",
    ["linux", "bash", "staged"],
    {
      templateId: "bash-curl-staged",
      lhost: "10.10.14.3",
      lport: 4444,
      httpPort: 8000,
      shell: "/bin/bash",
      obfuscation: "none",
    },
  ),
  preset(
    "web-rce-perl",
    "Web RCE Perl",
    "Perl reverse shell for targets with Perl and outbound TCP access.",
    ["multi", "perl", "web-rce"],
    {
      templateId: "perl-socket",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "/bin/sh",
      obfuscation: "url",
    },
  ),
  preset(
    "web-rce-ruby",
    "Web RCE Ruby",
    "Ruby TCPSocket payload for targets where Ruby is available.",
    ["multi", "ruby", "web-rce"],
    {
      templateId: "ruby-socket",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "/bin/sh",
      obfuscation: "url",
    },
  ),
  preset(
    "multi-nc-bind-e",
    "Bind shell netcat -e",
    "Bind shell preset for isolated labs where the operator connects inbound.",
    ["multi", "bind", "nc"],
    {
      templateId: "nc-bind-e",
      lhost: "0.0.0.0",
      lport: 4444,
      shell: "/bin/sh",
      obfuscation: "none",
    },
  ),
  preset(
    "multi-python3-bind",
    "Bind shell Python 3",
    "Python bind shell fallback when netcat -e is unavailable.",
    ["multi", "bind", "python"],
    {
      templateId: "python3-bind",
      lhost: "0.0.0.0",
      lport: 4444,
      shell: "/bin/sh",
      obfuscation: "none",
    },
  ),
  preset(
    "multi-python-bind",
    "Bind shell Python",
    "Unversioned Python bind shell fallback when netcat -e is unavailable.",
    ["multi", "bind", "python"],
    {
      templateId: "python-bind",
      lhost: "0.0.0.0",
      lport: 4444,
      shell: "/bin/sh",
      obfuscation: "none",
    },
  ),
  preset(
    "multi-python2-bind",
    "Bind shell Python 2",
    "Python 2 bind shell fallback for legacy targets.",
    ["multi", "bind", "python"],
    {
      templateId: "python2-bind",
      lhost: "0.0.0.0",
      lport: 4444,
      shell: "/bin/sh",
      obfuscation: "none",
    },
  ),
  preset(
    "web-rce-nodejs",
    "Web RCE Node.js",
    "Node.js reverse shell for targets with server-side JavaScript execution.",
    ["multi", "node", "web-rce"],
    {
      templateId: "nodejs-child-process",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "/bin/sh",
      obfuscation: "url",
    },
  ),
  preset(
    "linux-openssl-fifo",
    "Linux OpenSSL FIFO",
    "TLS callback using openssl s_client and a named pipe.",
    ["linux", "openssl", "tls"],
    {
      templateId: "openssl-fifo",
      lhost: "10.10.14.3",
      lport: 443,
      shell: "/bin/sh",
      obfuscation: "none",
    },
  ),
  preset(
    "linux-busybox-nc",
    "Linux BusyBox nc",
    "Compact BusyBox netcat payload for minimal Linux environments.",
    ["linux", "nc", "busybox"],
    {
      templateId: "busybox-nc-e",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "/bin/sh",
      obfuscation: "none",
    },
  ),
  preset(
    "linux-sh-dev-tcp",
    "Linux sh /dev/tcp",
    "POSIX sh reverse shell for targets where /dev/tcp is available.",
    ["linux", "sh", "classic"],
    {
      templateId: "sh-dev-tcp",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "/bin/sh",
      obfuscation: "none",
    },
  ),
  preset(
    "macos-bash-dev-tcp",
    "macOS Bash /dev/tcp",
    "macOS-friendly Bash callback using the platform-specific preset.",
    ["macos", "bash", "classic"],
    {
      templateId: "macos-bash-dev-tcp",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "/bin/bash",
      obfuscation: "none",
    },
  ),
  preset(
    "multi-ncat-ssl",
    "Ncat SSL reverse shell",
    "TLS callback using ncat --ssl for targets with OpenSSL-enabled ncat.",
    ["multi", "ncat", "tls", "encrypted"],
    {
      templateId: "ncat-ssl-exec",
      lhost: "10.10.14.3",
      lport: 443,
      shell: "/bin/sh",
      obfuscation: "none",
    },
  ),
  preset(
    "multi-python3-ssl",
    "Python 3 SSL reverse shell",
    "Python 3 TLS callback using ssl.wrap_socket.",
    ["multi", "python", "tls", "encrypted"],
    {
      templateId: "python3-ssl-socket",
      lhost: "10.10.14.3",
      lport: 443,
      shell: "/bin/sh",
      obfuscation: "none",
    },
  ),
  preset(
    "multi-nodejs-tls",
    "Node.js TLS reverse shell",
    "Node.js TLS callback using tls and child_process.",
    ["multi", "node", "tls", "encrypted"],
    {
      templateId: "nodejs-tls-child-process",
      lhost: "10.10.14.3",
      lport: 443,
      shell: "/bin/sh",
      obfuscation: "none",
    },
  ),
  preset(
    "web-rce-php-ssl",
    "Web RCE PHP SSL",
    "PHP TLS callback using ssl:// fsockopen.",
    ["multi", "php", "web-rce", "tls", "encrypted"],
    {
      templateId: "php-ssl-fsockopen",
      lhost: "10.10.14.3",
      lport: 443,
      shell: "/bin/sh",
      obfuscation: "url",
    },
  ),
  preset(
    "windows-powershell-tls",
    "Windows PowerShell TLS",
    "PowerShell reverse shell over TLS using SslStream.",
    ["windows", "powershell", "tls", "encrypted"],
    {
      templateId: "powershell-tls-schannel",
      lhost: "10.10.14.3",
      lport: 443,
      shell: "powershell.exe",
      obfuscation: "none",
    },
  ),
  preset(
    "web-rce-php-stream",
    "Web RCE PHP stream socket",
    "PHP stream_socket_client command loop for web RCE contexts.",
    ["multi", "php", "web-rce"],
    {
      templateId: "php-stream-socket-loop",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "/bin/sh",
      obfuscation: "url",
    },
  ),
  preset(
    "windows-cmd-powershell",
    "Windows CMD PowerShell TCP",
    "cmd.exe launcher for a compact PowerShell reverse shell.",
    ["windows", "cmd", "powershell"],
    {
      templateId: "cmd-powershell-tcp-reverse",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "cmd.exe",
      obfuscation: "none",
    },
  ),
  preset(
    "linux-busybox-wget-staged",
    "Linux BusyBox wget staged",
    "BusyBox wget loader that fetches a staged script from your HTTP server.",
    ["linux", "busybox", "staged"],
    {
      templateId: "staged-busybox-wget",
      lhost: "10.10.14.3",
      lport: 4444,
      httpPort: 8000,
      shell: "/bin/sh",
      obfuscation: "none",
    },
  ),
  preset(
    "linux-msfvenom-aarch64",
    "MSFvenom Linux aarch64",
    "Generate a Linux aarch64 shell_reverse_tcp ELF payload.",
    ["linux", "msfvenom"],
    {
      templateId: "msfvenom-linux-aarch64-elf",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "/bin/sh",
      obfuscation: "none",
    },
  ),
  preset(
    "windows-msfvenom-powershell",
    "MSFvenom PowerShell command",
    "Generate a raw PowerShell reverse TCP payload with msfvenom.",
    ["windows", "msfvenom", "powershell"],
    {
      templateId: "msfvenom-powershell-cmd",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "powershell.exe",
      obfuscation: "none",
    },
  ),
  preset(
    "linux-bash-url-double",
    "Bash URL double encoded",
    "Bash reverse shell with URL double encoding for nested decode contexts.",
    ["linux", "bash", "encoded"],
    {
      templateId: "bash-dev-tcp",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "/bin/bash",
      obfuscation: "url-double",
    },
  ),
  preset(
    "linux-bash-printf-hex",
    "Bash printf hex",
    "Bash payload rebuilt with printf hex escapes for filter-sensitive shells.",
    ["linux", "bash", "encoded"],
    {
      templateId: "bash-dev-tcp",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "/bin/bash",
      obfuscation: "bash-printf-hex",
    },
  ),
  preset(
    "windows-powershell-base64",
    "Windows PowerShell base64",
    "PowerShell TCPClient payload wrapped in a UTF-8 base64 decode launcher.",
    ["windows", "powershell", "encoded"],
    {
      templateId: "powershell-tcp-client",
      lhost: "10.10.14.3",
      lport: 4444,
      shell: "powershell.exe",
      obfuscation: "powershell-base64",
    },
  ),
];
